import { IntervieweeForm } from '@prisma/client';

export class IntervieweeEntity implements IntervieweeForm {
  id: number;
  generalInfo: string;
  fullName: string;
  email: string;
  city: string;
  age: number;
  race: string;
  genderIdentity: string;
  primarySecondaryEducation: string;
  academicBackground: string;
  volunteerWork: boolean;
  environmentalAgenda: boolean;
  environmentalInterest: boolean;
  noInvolvement: boolean;
  questions: string;
  knowledgeLevel: number;
  climateConcerns: number;
  agendaClimaticNews: boolean;
  agendaClimaticSchool: boolean;
  agendaClimaticConversations: boolean;
  agendaClimaticCommunities: boolean;
  agendaClimaticWithoutExposure: boolean;
  greenJob: boolean;
  carbonMarket: boolean;
  climateJustice: boolean;
  globalWarming: boolean;
  unafm: boolean;
  sustainableDevelopment: boolean;
  climateAction: boolean;
  waterCrisis: boolean;
  impactAgricultureGasEmissions: boolean;
  importancePreservingAmazonForest: boolean;
  esg: boolean;
  heardAboutOilExploration: string;
  consumptionOutweighsEcologicalResources: string;
  descriptionFinal: string;
  campinasChanges: string;
  comments: string;
  dataPermission: boolean;
  createdAt: Date;
}
